"""Project scaffolding for guarded AI agent apps."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent


@dataclass(frozen=True)
class ScaffoldResult:
    """Result from creating a starter project."""

    path: Path
    files_created: tuple[Path, ...]


def init_project(path: Path, *, force: bool = False) -> ScaffoldResult:
    """Create a guarded AI-agent application scaffold."""

    target = path.resolve()
    if target.exists() and any(target.iterdir()) and not force:
        raise FileExistsError(f"Target is not empty: {target}")

    files = {
        "README.md": _readme(target.name),
        "AGENTS.md": _agents_md(),
        "pyproject.toml": _pyproject(target.name),
        ".gitignore": _gitignore(),
        ".github/workflows/quality.yml": _quality_workflow(),
        "src/app/__init__.py": '"""Generated agent app."""\n',
        "src/app/main.py": _main_py(),
        "tests/test_smoke.py": _smoke_test(),
        "evals/basic_cases.json": _eval_cases(),
        "examples/run_local.py": _example_run(),
    }

    created: list[Path] = []
    for relative, content in files.items():
        file_path = target / relative
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        created.append(file_path)

    return ScaffoldResult(path=target, files_created=tuple(created))


def _readme(name: str) -> str:
    return dedent(
        f"""\
        # {name}

        Guarded AI-agent app generated by AgentOps Starter Kit.

        ## Run

        ```bash
        uv sync --extra dev
        uv run python examples/run_local.py
        uv run pytest
        ```

        The default path uses a deterministic fake model, so it works offline and without API keys.

        ## Guardrails

        - Tests must pass before changes are merged.
        - Live model calls should be behind provider adapters.
        - Evals live in `evals/` and should cover critical behavior.
        - Tool calls should be logged and budgeted.
        - Secrets must stay out of source control.
        """
    )


def _agents_md() -> str:
    return dedent(
        """\
        # Agent Instructions

        - Use `uv` for Python commands.
        - Run `uv run pytest` before committing.
        - Keep live LLM/API calls out of unit tests.
        - Add or update eval cases when changing agent behavior.
        - Do not commit secrets, `.env`, or local model credentials.
        - Prefer small, reviewable changes with clear telemetry.
        """
    )


def _pyproject(name: str) -> str:
    return dedent(
        f"""\
        [project]
        name = "{name}"
        version = "0.1.0"
        requires-python = ">=3.11"
        dependencies = []

        [project.optional-dependencies]
        dev = ["pytest>=8.0.0", "ruff>=0.8.0"]

        [build-system]
        requires = ["hatchling"]
        build-backend = "hatchling.build"

        [tool.hatch.build.targets.wheel]
        packages = ["src/app"]

        [tool.ruff]
        line-length = 100
        target-version = "py311"

        [tool.pytest.ini_options]
        testpaths = ["tests"]
        addopts = "-q"
        """
    )


def _gitignore() -> str:
    return dedent(
        """\
        .venv/
        __pycache__/
        .pytest_cache/
        .ruff_cache/
        .env
        .env.*
        runs/
        """
    )


def _quality_workflow() -> str:
    return dedent(
        """\
        name: Quality

        on:
          push:
          pull_request:

        jobs:
          test:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: astral-sh/setup-uv@v5
              - run: uv sync --extra dev
              - run: uv run ruff check .
              - run: uv run ruff format --check .
              - run: uv run pytest
        """
    )


def _main_py() -> str:
    return dedent(
        """\
        from dataclasses import dataclass


        @dataclass(frozen=True)
        class AgentRun:
            task: str
            answer: str
            cost_usd: float = 0.0


        def run_agent(task: str) -> AgentRun:
            return AgentRun(
                task=task,
                answer=f"Offline demo answer for: {task}",
            )
        """
    )


def _smoke_test() -> str:
    return dedent(
        """\
        from app.main import run_agent


        def test_run_agent_offline() -> None:
            result = run_agent("summarize support tickets")

            assert result.answer.startswith("Offline demo answer")
            assert result.cost_usd == 0.0
        """
    )


def _eval_cases() -> str:
    return dedent(
        """\
        [
          {
            "name": "offline_smoke",
            "task": "summarize support tickets",
            "expected_contains": "Offline demo answer"
          }
        ]
        """
    )


def _example_run() -> str:
    return dedent(
        """\
        from app.main import run_agent


        if __name__ == "__main__":
            result = run_agent("summarize support tickets")
            print(result.answer)
        """
    )
